name: CI

on:
  # Run on pull requests to main
  pull_request:
    branches: [ main ]
  
  # Run on pushes to any branch except main (for PR branches)
  push:
    branches-ignore: [ main ]

  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  test:
    name: Tests and Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python 3.13
      run: uv python install 3.13
      
    - name: Install dependencies
      run: uv sync
      
    - name: Run code formatting check
      run: uv run ruff format --check .
      
    - name: Run linting checks
      run: uv run ruff check .
        
    - name: Run test suite
      run: uv run pytest -v --tb=short
      
    - name: Test CLI functionality
      run: |
        # Test basic CLI commands work
        uv run lse --help
        uv run lse report --help
        echo "✅ CLI commands working correctly"